<?php 
session_start();
if(!isset($_SESSION["employee_id"])){
	header("Location:pgEmployeeLogIn.php");
}
// Include class definition
include_once "function.php";
include_once "commonFunctions.php";
$sign=new Signup();
$commonfunction=new Common();

$company_id=$_SESSION["company_id"];
$ewayid=$_REQUEST["id"];
$outwardid=$_REQUEST["outward_id"];
date_default_timezone_set("Asia/Kolkata");
$cur_date=date("Y-m-d h:i:sa");

$qry = "SELECT sender_company_id,receiver_company_id,outward_id,valid_upto,mode_transportation,mode_transportation,approx_distance,eway_bill_type,transaction_type,address_id_sender,address_id_receiver,transporter_id,vehicle_id,created_on from  tw_material_outward_eway WHERE id = ".$ewayid." ";
$retVal = $sign->FunctionJSON($qry);
$decodedJSON = json_decode($retVal);
$sender_company_id= $decodedJSON->response[0]->sender_company_id;
$receiver_company_id = $decodedJSON->response[1]->receiver_company_id; 
$outward_id = $decodedJSON->response[2]->outward_id; 
$valid_upto = $decodedJSON->response[3]->valid_upto;
$mode_transportation = $decodedJSON->response[4]->mode_transportation;
$approx_distance = $decodedJSON->response[5]->approx_distance;
$eway_bill_type = $decodedJSON->response[6]->eway_bill_type;
$transaction_type = $decodedJSON->response[7]->transaction_type;
$address_id_sender = $decodedJSON->response[8]->address_id_sender;
$address_id_receiver = $decodedJSON->response[9]->address_id_receiver;
$transporter_id = $decodedJSON->response[10]->transporter_id;
$vehicle_id = $decodedJSON->response[11]->vehicle_id;
$created_on = $decodedJSON->response[12]->created_on;
$srno = $ewayid;


$qry2="SELECT tm.transporter_name,tk.document_number  FROM tw_transport_master tm INNER JOIN  tw_transporter_kyc tk ON tm.id = tk.transporter_id WHERE tm.id='".$transporter_id."'";
$retVal2 = $sign->FunctionJSON($qry2);
$decodedJSON = json_decode($retVal2);
$transporter_name= $decodedJSON->response[0]->transporter_name;
$document_number = $decodedJSON->response[1]->document_number; 

$qry3="SELECT vehicle_number FROM tw_vehicle_details_master WHERE transporter_id='".$transporter_id."'";
$retVal3 = $sign->SelectF($qry3,"vehicle_number");

$qry4="SELECT cd.CompanyName,cdo.document_number FROM tw_company_details cd INNER JOIN tw_company_document cdo ON cd.ID=cdo.company_id  WHERE cd.ID='".$company_id."'";
$retVal4 = $sign->FunctionJSON($qry4);
$decodedJSON = json_decode($retVal4);
$CompanyName= $decodedJSON->response[0]->CompanyName;
$gst_number = $decodedJSON->response[1]->document_number; 


$qryo = "SELECT company_address,bill_to,ship_to,customer_id from tw_material_outward WHERE id = ".$outwardid." ";
$retValo = $sign->FunctionJSON($qryo);
$decodedJSON = json_decode($retValo);
$company_address= $decodedJSON->response[0]->company_address;
$bill_to= $decodedJSON->response[1]->bill_to;
$ship_to= $decodedJSON->response[2]->ship_to;
$customer_id= $decodedJSON->response[3]->customer_id;

$qryo1 = "SELECT address_line1,address_line2,location,pincode,city,state FROM tw_company_address WHERE id = ".$company_address." ";
$retValo1 = $sign->FunctionJSON($qryo1);
$decodedJSON = json_decode($retValo1);
$caddress_line1= $decodedJSON->response[0]->address_line1;
$caddress_line2= $decodedJSON->response[1]->address_line2;
$clocation= $decodedJSON->response[2]->location;
$cpincode= $decodedJSON->response[3]->pincode;
$ccity= $decodedJSON->response[4]->city;
$cstate= $decodedJSON->response[5]->state;

//$caddress = $caddress_line1+$caddress_line2+$clocation+$cpincode+$ccity+$cstate;

$qryo2 = "SELECT address_line1,address_line2,location,pincode,city,state FROM tw_company_address WHERE id = ".$ship_to." ";
$retValo2 = $sign->FunctionJSON($qryo2);
$decodedJSON = json_decode($retValo2);
$saddress_line1= $decodedJSON->response[0]->address_line1;
$saddress_line2= $decodedJSON->response[1]->address_line2;
$slocation= $decodedJSON->response[2]->location;
$spincode= $decodedJSON->response[3]->pincode;
$scity= $decodedJSON->response[4]->city;
$sstate= $decodedJSON->response[5]->state;


$qry5="SELECT cd.CompanyName,cdo.document_number FROM tw_company_details cd INNER JOIN tw_company_document cdo ON cd.ID=cdo.company_id  WHERE cd.ID='".$customer_id."'";
$retVal5 = $sign->FunctionJSON($qry5);
$decodedJSON = json_decode($retVal5);
$CustomerCompanyName= $decodedJSON->response[0]->CompanyName;
$Customergst_number = $decodedJSON->response[1]->document_number; 

?>
<html>
<head>
<title>eWayBill</title>
</head>
<body>
<h1><center>e-Way Bill</center></h1>

<table width="100%" border="1">
	<tr>
		<td colspan="3">1. E-WAY BILL Details</td>
	</tr>
	<tr>
		<td>eWay Bill No: <?php echo $srno; ?></td>
		<td>Generated Date: <?php echo $created_on; ?> | Generated By: <?php echo $gst_number; ?></td>
		<td>Valid Upto: <?php echo $valid_upto; ?></td> 
	</tr>
	<tr>
		<td>Mode: <?php echo $mode_transportation; ?></td>
		<td>Approx Distance: <?php echo $approx_distance; ?></td>
		<td></td>
	</tr>
	<tr>
		<td>Type: Outward - <?php echo $eway_bill_type; ?></td>
		<td>Document Detail: Tax Invoice- RTPL/MH/017 - 07/10/2021</td>
		<td>Transaction type: <?php echo $transaction_type; ?> </td>
	</tr>
</table>
<table width="100%" border="1">
	<tr>
		<td colspan="2"> 2. Address Details </td>
	</tr>
	<tr>
		<td>From </td>
		<td>To</td> 
	</tr>
	<tr>
		<td>
			GSTIN:<?php echo $gst_number; ?><br>
			<?php echo $CompanyName; ?><br>
			<?php echo $cstate; ?>
		</td>
		<td>
			GSTIN:<?php echo $Customergst_number; ?><br>
			<?php echo $CustomerCompanyName; ?><br>
			<?php echo $sstate; ?>
		</td>
	</tr>
	<tr>
		<td>
			=Dispatch From=<br>
			<?php echo $caddress_line1." ".$caddress_line2; ?><br>
			<?php echo $clocation; ?><br>
			<?php echo $ccity."-".$cpincode." ".$cstate; ?>
		</td>
		<td>
			=Ship To=<br>
			<?php echo $saddress_line1." ".$saddress_line2; ?><br>
			<?php echo $slocation; ?><br>
			<?php echo $scity."-".$spincode." ".$sstate; ?>
		</td>
	</tr>
</table>

<table width="100%" border="1">
	<tr>
		<td colspan="5">3. Goods Details</td>
	</tr>
	<tr>
		<td width="5%">HSN Code</td>
		<td width="65%">Product Name &amp; Desc.</td>
		<td width="10%">Quantity</td>
		<td width="10%">Taxable Amount Rs.</td>
		<td width="10%">Tax Rate(C+S+Cess+Cess Non.Advol)</td>
	</tr>
	
		<?php 
			$qry1 = "select pm.product_name,pm.hsn,moi.quantity,moi.tax,moi.rate,moi.total from tw_material_outward_individual moi INNER JOIN tw_product_management pm ON moi.material_id=pm.id WHERE moi.material_outward_id='".$outward_id."' ORDER BY moi.id";
			$retVal1 = $sign->FunctionJSON($qry1);
			
			$qry2="Select count(*) as cnt from tw_material_outward_individual where material_outward_id = '".$outwardid."' ORDER BY id DESC";
			$retVal2 = $sign->Select($qry2);

			$decodedJSON2 = json_decode($retVal1);
			$count = 0;
			$i = 1;
			$x=$retVal2;
			$totaltaxableamount=0;
			$valtotalamt=0;
			$it=1;
		 	 while($x>=$i){
					$product_name = $decodedJSON2->response[$count]->product_name;
					$count=$count+1;
					$hsn = $decodedJSON2->response[$count]->hsn;
					$count=$count+1;
					$quantity = $decodedJSON2->response[$count]->quantity;
					$count=$count+1;
					$tax = $decodedJSON2->response[$count]->tax;
					$count=$count+1;
					$rate = $decodedJSON2->response[$count]->rate;
					$count=$count+1;
					$total = $decodedJSON2->response[$count]->total;
					$count=$count+1;
					$totaltaxableamount=$totaltaxableamount+$tax;
					$temptotal = ($quantity*$rate);
					$temptax = $temptotal * ($tax/100);
					$valtotalamt = $valtotalamt+$temptotal+$temptax;
					
					$it++;
					$i=$i+1; 
					
					?>
					
					<tr>
						<td><?php echo $hsn; ?></td>
						<td><?php echo $product_name; ?></td>
						<td><?php echo $quantity; ?></td>
						<td><?php echo $tax; ?></td>
						<td>Pending</td>
					</tr>
					<?php
						}					
			
					?>
			
</table>
<table width="100%" border="1">
	<tr>
		<td width="25%">TOT. Taxable Amt <?php echo $totaltaxableamount; ?>  </td>
		<td width="25%">CGST Amt 0.00    </td>
		<td width="25%">SGST 0.00   </td>
		<td width="25%">IGST Amt 65446.92  </td>
	</tr> 
	<tr>
		<td width="25%">CESS Amt 0.00 </td>
		<td width="25%">CESS Non.Advol Amt 0.00</td>
		<td width="25%">Other Amt 4290.41  </td>
		<td width="25%">  Total Inv. Amt <?php echo $valtotalamt; ?> </td>
	</tr>
</table>
<table width="100%" border="1">
	<tr>
		<td colspan="4">4. Transportation Details</td>
	</tr>
	<tr>
		<td>Transporter ID</td>
		<td>Transporter Name</td>
		<td>Transporter Doc No
		<td>Date</td>
	</tr>
	<tr>
		<td><?php echo $transporter_id; ?></td>
		<td><?php echo $transporter_name; ?></td>
		<td><?php echo $document_number; ?></td>
		<td><?php echo $cur_date; ?></td>
	</tr>
</table>

<table width="100%" border="1">
	<tr>
		<td colspan="7"> 5. Vehicle Details    </td>
	</tr>
	<tr>
		<td>Mode</td>
		<td>Vehicle / Trans Doc No &amp; DL</td>
        <td>From</td>
        <td>Entered Date</td>
        <td>Entered By</td>
        <td>CEBW No. (if any)</td>
        <td>Multi Veh. Info (if any)\</td>
	</tr>
	<tr>
		<td>Road</td>
		<td>MH03CV6911</td>
        <td>MAROL ANDHERI EAST MUMBAI</td>
        <td>07/10/2021 09:19 PM</td>
        <td>27AAHCR110982ZV</td>
        <td></td>
		<td></td>
	</tr>
</tbody></table>















    
    
</body></html>